version: '3.8'

networks:
  app-shared:
    driver: bridge

services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/var/www/html
    ports:
      - 8000:8000
    depends_on:
      - postgres_db
    networks:
      - app-shared

  postgres_db:
    image: postgres
    restart: always
    environment:            
      POSTGRES_USER: postgres      
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: knwein
    volumes:
      - ./storage/dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app-shared